import * as fs from "fs";
import { cloneRepo, readFileFromRepo, applyPatch, createBranchAndPush, createBranchWithNewFile } from "../shared/git-client";
import { invokeClaudeJson } from "../shared/bedrock-client";
import { storeAuditLog, writePipelineState, readPipelineState } from "../shared/s3-client";
import { buildFixPrompt, FIX_SYSTEM_PROMPT } from "./prompts";
import { PipelineState, FixResult, EnrichedHealerEvent } from "../../lambdas/shared/types";

// TODO: Add your project's source directories here.
// The AI will only apply diffs to files under these prefixes.
const SAFE_PATH_PREFIXES = [
  "src/",
  "lib/",
  "app/",
  "packages/",
  "server/",
  "api/",
];

const FORBIDDEN_PATH_PATTERNS = [
  /^infrastructure\//,
  /^\.github\//,
  /^\.husky\//,
  /migrations\//,
  /^Dockerfile/,
  /\.ya?ml$/,
  /\.sh$/,
];

const validateAffectedFiles = (files: string[]): { safe: boolean; reason?: string } => {
  for (const f of files) {
    const inSafePrefix = SAFE_PATH_PREFIXES.some((prefix) => f.startsWith(prefix));
    const matchesForbidden = FORBIDDEN_PATH_PATTERNS.some((pattern) => pattern.test(f));
    if (!inSafePrefix || matchesForbidden) {
      return { safe: false, reason: `File path not in allowlist: ${f}` };
    }
  }
  return { safe: true };
};

const slugify = (title: string) =>
  title
    .toLowerCase()
    .replace(/[^a-z0-9]+/g, "-")
    .slice(0, 40);

const main = async () => {
  const executionId = process.env.EXECUTION_ID;
  if (!executionId) throw new Error("EXECUTION_ID env var required");

  const state = await readPipelineState<PipelineState>(executionId);
  const { investigation } = state;
  if (!investigation) throw new Error("No investigation in state");

  const { repoPath, git } = await cloneRepo();
  let branchName: string | undefined;
  let parsed!: FixResult;
  try {
  const event = (state.enriched ?? state.event) as EnrichedHealerEvent;

  const fileContents: Record<string, string> = {};
  for (const f of investigation.affectedFiles) {
    const content = readFileFromRepo(repoPath, f);
    if (content) fileContents[f] = content;
  }

  const userPrompt = buildFixPrompt(event, investigation, fileContents);

  let raw = "";
  try {
    const result = await invokeClaudeJson<FixResult>(FIX_SYSTEM_PROMPT, userPrompt);
    raw = result.raw;
    parsed = result.parsed;
    await storeAuditLog(executionId, "fix", {
      prompt: userPrompt,
      response: raw,
      metadata: { tokens: result.tokens, fixType: parsed.type },
    });
  } catch (err) {
    await storeAuditLog(executionId, "fix-error", {
      prompt: userPrompt,
      response: raw,
      metadata: { error: String(err) },
    });
    throw err;
  }

  if (parsed!.type === "code-fix" && parsed!.diff) {
    const pathCheck = validateAffectedFiles(parsed!.affectedFiles);
    if (!pathCheck.safe) {
      console.warn(`[FIX] Rejected fix — unsafe file paths: ${pathCheck.reason}`);
      parsed!.type = "investigation-only";
      parsed!.explanation = `Fix rejected: ${pathCheck.reason}`;
    }
  }

  if (parsed!.type === "code-fix" && parsed!.diff) {
    try {
      applyPatch(repoPath, parsed!.diff);
      const date = new Date().toISOString().slice(0, 10);
      const suffix = executionId.slice(-6);
      branchName = `healer/${date}-${slugify(event.title)}-${suffix}`;
      const msg = `fix(healer): ${event.title.slice(0, 72)}\n\nAuto-generated by self-healing pipeline.\nExecution: ${executionId}`;
      await createBranchAndPush(git, branchName, msg, parsed!.affectedFiles);
      console.log(`[FIX] Pushed branch: ${branchName}`);
    } catch (err) {
      console.error("[FIX] Patch apply failed, downgrading to investigation-only:", err);
      parsed!.type = "investigation-only";
      parsed!.explanation = `Patch failed: ${err instanceof Error ? err.message : String(err)}`;
      branchName = undefined;
    }
  }

  // Investigation-only: push a HEALER_REPORT.md so StagePR always has a commit to PR.
  if (!branchName && parsed!.type === "investigation-only") {
    const date = new Date().toISOString().slice(0, 10);
    const suffix = executionId.slice(-6);
    branchName = `healer/${date}-${slugify(event.title)}-${suffix}`;
    const report = [
      `# Healer Investigation Report`,
      ``,
      `**Execution:** ${executionId}`,
      `**Date:** ${date}`,
      `**Issue:** ${event.title}`,
      `**Confidence:** below threshold — no code fix generated`,
      ``,
      `## Root Cause`,
      parsed!.explanation ?? "No root cause identified.",
      ``,
      `## Recommendation`,
      `Manual review required. This PR contains the investigation report only.`,
    ].join("\n");
    try {
      await createBranchWithNewFile(git, repoPath, branchName, "HEALER_REPORT.md", report,
        `chore(healer): investigation report — ${event.title.slice(0, 60)}\n\nNo code fix generated (confidence below threshold).\nExecution: ${executionId}`);
      console.log(`[FIX] Pushed report-only branch: ${branchName}`);
    } catch (err) {
      console.warn("[FIX] Could not push report branch:", err);
      branchName = undefined;
    }
  }

  } finally {
    fs.rmSync(repoPath, { recursive: true, force: true });
  }

  const updated: PipelineState = {
    ...state,
    fix: parsed!,
    // Store branchName in state so test/run.ts can read it (fixes C7)
    ...(branchName ? { branchName } : {}),
  };

  await writePipelineState(updated);
  console.log(`[FIX] State written to S3 for execution ${executionId}`);
};

main().catch((err) => {
  console.error("[FIX] Fatal:", err);
  process.exit(1);
});
